services:
  - type: web
    name: protein-insight
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=200
